seed: 42

train_hic: "processed_data/hic_embedding/trainseq_trainbio.npy"
train_seq: "processed_data/seq_embedding/train.npy"
train_y: "processed_data/labels/label_trainseq_trainbio.npy"

val_hic: "processed_data/hic_embedding/valseq_valbio.npy"
val_seq: "processed_data/seq_embedding/val.npy"
val_y: "processed_data/labels/label_valseq_valbio.npy"

use_wandb: False
wandb_project: "Puget"
logger_name: "puget_cls_dim512_layer4_lr1e-4_batch64_seed42"
logger_dir: "csv_logs"
model_dir: "models/puget_decoder"

embed_dim: 3072
seq_weights_path: null

proj_dim: 512
mlp_ratio: 4.0
num_heads: 16
num_layers: 4
pool_method: "cls"
dropout_p: 0.2

hic2seq_ratio: 125
ratios: [5, 5, 5]
align_to: "rows"
seq_pad_mode: "zeros"
seq_scale: 1.0
add_layernorm: True
ln_elementwise_affine: False

lr: 1.0e-4
min_lr: 1.0e-7
weight_decay: 1.0e-4
warmup_epochs: 2
decay_epochs: 18

max_epochs: 20
batch_size: 64
num_workers: 8
patience: 40
val_check_interval: 0.5
precision: "16-mixed"
accumulate_grad_batches: 1
