# Experiment Settings
device: "cuda"
batch_size: 1
num_workers: 1

# Output Paths
output_dir: "outputs/interpretation/attribution"
seq_attr_filename: "gradientxinput_seq_k562.npy"
hic_attr_filename: "gradientxinput_hic_k562.npy"

# Data Paths
bedpe_path: "data/gene_annotations/human_anno_tss_filtered_192k_960k_test.bedpe"
pkl_list_file: "data/accessions/hiclist_k562.csv"
pkl_data_dir: "data/example_input"
seq_indices_npy: "data/example_input/humanseq_test_indices.npy"

# Checkpoint Paths
enformer_ckpt: "data/model/retrain_enformer.pt"
hic_encoder_ckpt: "data/model/hicfoundation_pretrain.pth.tar"
regressor_ckpt: "data/model/puget_decoder.ckpt"

# Model Params
model:
  name: "vit_large_patch16"
  patch_size: 16
  window_height: 192
  window_width: 960
  resolution: 1000
  seq_length: 192000
